{
    "discoveryVersion": "v1",
    "version_module": true,
    "protocol": "rest",
    "canonicalName": "Vault",
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/ediscovery.readonly": {
                    "description": "View your eDiscovery data"
                },
                "https://www.googleapis.com/auth/ediscovery": {
                    "description": "Manage your eDiscovery data"
                }
            }
        }
    },
    "rootUrl": "https://vault.googleapis.com/",
    "ownerDomain": "google.com",
    "name": "vault",
    "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
    "batchPath": "batch",
    "fullyEncodeReservedExpansion": true,
    "title": "G Suite Vault API",
    "ownerName": "Google",
    "resources": {
        "operations": {
            "methods": {
                "delete": {
                    "description": "Deletes a long-running operation. This method indicates that the client is\nno longer interested in the operation result. It does not cancel the\noperation. If the server doesn't support this method, it returns\n`google.rpc.Code.UNIMPLEMENTED`.",
                    "httpMethod": "DELETE",
                    "flatPath": "v1/operations/{operationsId}",
                    "path": "v1/{+name}",
                    "id": "vault.operations.delete"
                }
            }
        },
        "matters": {
            "methods": {
                "create": {
                    "description": "Creates a new matter with the given name and description. The initial state\nis open, and the owner is the method caller. Returns the created matter\nwith default view.",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters",
                    "id": "vault.matters.create",
                    "path": "v1/matters"
                },
                "removePermissions": {
                    "flatPath": "v1/matters/{matterId}:removePermissions",
                    "path": "v1/matters/{matterId}:removePermissions",
                    "id": "vault.matters.removePermissions",
                    "description": "Removes an account as a matter collaborator.",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ]
                },
                "reopen": {
                    "path": "v1/matters/{matterId}:reopen",
                    "id": "vault.matters.reopen",
                    "description": "Reopens the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}:reopen"
                },
                "close": {
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}:close",
                    "path": "v1/matters/{matterId}:close",
                    "id": "vault.matters.close",
                    "description": "Closes the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST"
                },
                "undelete": {
                    "description": "Undeletes the specified matter. Returns matter with updated state.",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}:undelete",
                    "id": "vault.matters.undelete",
                    "path": "v1/matters/{matterId}:undelete"
                },
                "get": {
                    "path": "v1/matters/{matterId}",
                    "id": "vault.matters.get",
                    "description": "Gets the specified matter.",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ],
                    "flatPath": "v1/matters/{matterId}"
                },
                "update": {
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}",
                    "path": "v1/matters/{matterId}",
                    "id": "vault.matters.update",
                    "description": "Updates the specified matter.\nThis updates only the name and description of the matter, identified by\nmatter ID. Changes to any other fields are ignored.\nReturns the default view of the matter."
                },
                "delete": {
                    "description": "Deletes the specified matter. Returns matter with updated state.",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}",
                    "id": "vault.matters.delete",
                    "path": "v1/matters/{matterId}"
                },
                "addPermissions": {
                    "id": "vault.matters.addPermissions",
                    "path": "v1/matters/{matterId}:addPermissions",
                    "description": "Adds an account as a matter collaborator.",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery"
                    ],
                    "flatPath": "v1/matters/{matterId}:addPermissions"
                },
                "list": {
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/ediscovery",
                        "https://www.googleapis.com/auth/ediscovery.readonly"
                    ],
                    "flatPath": "v1/matters",
                    "path": "v1/matters",
                    "id": "vault.matters.list",
                    "description": "Lists matters the user has access to."
                }
            },
            "resources": {
                "savedQueries": {
                    "methods": {
                        "get": {
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "id": "vault.matters.savedQueries.get",
                            "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "description": "Retrieves a saved query by Id.",
                            "httpMethod": "GET"
                        },
                        "list": {
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/savedQueries",
                            "id": "vault.matters.savedQueries.list",
                            "path": "v1/matters/{matterId}/savedQueries",
                            "description": "Lists saved queries within a matter. An empty page token in\nListSavedQueriesResponse denotes no more saved queries to list."
                        },
                        "create": {
                            "flatPath": "v1/matters/{matterId}/savedQueries",
                            "path": "v1/matters/{matterId}/savedQueries",
                            "id": "vault.matters.savedQueries.create",
                            "description": "Creates a saved query.",
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        },
                        "delete": {
                            "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
                            "id": "vault.matters.savedQueries.delete",
                            "description": "Deletes a saved query by Id.",
                            "httpMethod": "DELETE",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ]
                        }
                    }
                },
                "holds": {
                    "methods": {
                        "delete": {
                            "httpMethod": "DELETE",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}",
                            "id": "vault.matters.holds.delete",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold."
                        },
                        "list": {
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds",
                            "path": "v1/matters/{matterId}/holds",
                            "id": "vault.matters.holds.list",
                            "description": "Lists holds within a matter. An empty page token in ListHoldsResponse\ndenotes no more holds to list."
                        },
                        "create": {
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds",
                            "path": "v1/matters/{matterId}/holds",
                            "id": "vault.matters.holds.create",
                            "description": "Creates a hold in the given matter."
                        },
                        "removeHeldAccounts": {
                            "description": "Removes HeldAccounts from a hold. Returns a list of statuses in the same\norder as the request. If this request leaves the hold with no held\naccounts, the hold will not apply to any accounts.",
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
                            "id": "vault.matters.holds.removeHeldAccounts",
                            "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts"
                        },
                        "get": {
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "id": "vault.matters.holds.get",
                            "description": "Gets a hold by ID.",
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}"
                        },
                        "addHeldAccounts": {
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
                            "id": "vault.matters.holds.addHeldAccounts",
                            "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
                            "description": "Adds HeldAccounts to a hold. Returns a list of accounts that have been\nsuccessfully added. Accounts can only be added to an existing account-based\nhold."
                        },
                        "update": {
                            "httpMethod": "PUT",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/holds/{holdId}",
                            "id": "vault.matters.holds.update",
                            "path": "v1/matters/{matterId}/holds/{holdId}",
                            "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts\nto a hold that covers an OU, nor can you add OUs to a hold that covers\nindividual accounts. Accounts listed in the hold will be ignored."
                        }
                    },
                    "resources": {
                        "accounts": {
                            "methods": {
                                "list": {
                                    "description": "Lists HeldAccounts for a hold. This will only list individually specified\nheld accounts. If the hold is on an OU, then use\n<a href=\"https://developers.google.com/admin-sdk/\">Admin SDK</a>\nto enumerate its members.",
                                    "httpMethod": "GET",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery",
                                        "https://www.googleapis.com/auth/ediscovery.readonly"
                                    ],
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "id": "vault.matters.holds.accounts.list"
                                },
                                "create": {
                                    "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that\nhas no held_org_unit set. Attempting to add an account to an OU-based\nhold will result in an error.",
                                    "httpMethod": "POST",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ],
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                                    "id": "vault.matters.holds.accounts.create"
                                },
                                "delete": {
                                    "description": "Removes a HeldAccount from a hold. If this request leaves the hold with\nno held accounts, the hold will not apply to any accounts.",
                                    "httpMethod": "DELETE",
                                    "scopes": [
                                        "https://www.googleapis.com/auth/ediscovery"
                                    ],
                                    "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                                    "id": "vault.matters.holds.accounts.delete",
                                    "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                                }
                            }
                        }
                    }
                },
                "exports": {
                    "methods": {
                        "create": {
                            "httpMethod": "POST",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/exports",
                            "id": "vault.matters.exports.create",
                            "path": "v1/matters/{matterId}/exports",
                            "description": "Creates an Export."
                        },
                        "delete": {
                            "description": "Deletes an Export.",
                            "httpMethod": "DELETE",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery"
                            ],
                            "flatPath": "v1/matters/{matterId}/exports/{exportId}",
                            "path": "v1/matters/{matterId}/exports/{exportId}",
                            "id": "vault.matters.exports.delete"
                        },
                        "get": {
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/exports/{exportId}",
                            "path": "v1/matters/{matterId}/exports/{exportId}",
                            "id": "vault.matters.exports.get",
                            "description": "Gets an Export."
                        },
                        "list": {
                            "httpMethod": "GET",
                            "scopes": [
                                "https://www.googleapis.com/auth/ediscovery",
                                "https://www.googleapis.com/auth/ediscovery.readonly"
                            ],
                            "flatPath": "v1/matters/{matterId}/exports",
                            "id": "vault.matters.exports.list",
                            "path": "v1/matters/{matterId}/exports",
                            "description": "Lists Exports."
                        }
                    }
                }
            }
        }
    },
    "version": "v1",
    "baseUrl": "https://vault.googleapis.com/",
    "kind": "discovery#restDescription",
    "description": "Archiving and eDiscovery for G Suite.",
    "servicePath": "",
    "basePath": "",
    "revision": "20200501",
    "id": "vault:v1",
    "documentationLink": "https://developers.google.com/vault"
}
